#
# PlayerCount
#
update_message: true
use_custom_file: true
first_join:
  use: true
  broadcast: true
  text:
  - '&a&o{player}&f&o is the (&e&o{total}#&r)&o player on this server!'
  - '&f&oThank you for playing!'
default_join:
  use: true
  broadcast: false
  text:
  - '&f&oYou joined as (&e&o{number}#&r)&o on this server!'
  - '&f&oThank you for playing!'
counts: 1