main: com.twanl.playercount.PlayerCount
version: 2.0.0
name: PlayerCount
author: T.L

commands:
  playercount:
    usage: /<command>
    description: reload the config file
    aliases: [playercount, pc]